/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as PrepararEntrevistaRouteImport } from './routes/preparar-entrevista'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPaysuiteWebhookRouteImport } from './routes/api/paysuite-webhook'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMeusCvsRouteImport } from './routes/_authenticated/meus-cvs'
import { Route as AuthenticatedEntrevistasRouteImport } from './routes/_authenticated/entrevistas'
import { Route as AuthenticatedCartasRouteImport } from './routes/_authenticated/cartas'
import { Route as AuthenticatedCartaEditorRouteImport } from './routes/_authenticated/carta-editor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiCronPlanRemindersRouteImport } from './routes/api/cron/plan-reminders'
import { Route as ApiCronAiCostAlertRouteImport } from './routes/api/cron/ai-cost-alert'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepararEntrevistaRoute = PrepararEntrevistaRouteImport.update({
  id: '/preparar-entrevista',
  path: '/preparar-entrevista',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaysuiteWebhookRoute = ApiPaysuiteWebhookRouteImport.update({
  id: '/api/paysuite-webhook',
  path: '/api/paysuite-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusCvsRoute = AuthenticatedMeusCvsRouteImport.update({
  id: '/meus-cvs',
  path: '/meus-cvs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrevistasRoute =
  AuthenticatedEntrevistasRouteImport.update({
    id: '/entrevistas',
    path: '/entrevistas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartasRoute = AuthenticatedCartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartaEditorRoute =
  AuthenticatedCartaEditorRouteImport.update({
    id: '/carta-editor',
    path: '/carta-editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCronPlanRemindersRoute = ApiCronPlanRemindersRouteImport.update({
  id: '/api/cron/plan-reminders',
  path: '/api/cron/plan-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAiCostAlertRoute = ApiCronAiCostAlertRouteImport.update({
  id: '/api/cron/ai-cost-alert',
  path: '/api/cron/ai-cost-alert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/planos': typeof PlanosRoute
  '/preparar-entrevista': typeof PrepararEntrevistaRoute
  '/vagas': typeof VagasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carta-editor': typeof AuthenticatedCartaEditorRoute
  '/cartas': typeof AuthenticatedCartasRoute
  '/entrevistas': typeof AuthenticatedEntrevistasRoute
  '/meus-cvs': typeof AuthenticatedMeusCvsRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/paysuite-webhook': typeof ApiPaysuiteWebhookRoute
  '/api/cron/ai-cost-alert': typeof ApiCronAiCostAlertRoute
  '/api/cron/plan-reminders': typeof ApiCronPlanRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/planos': typeof PlanosRoute
  '/preparar-entrevista': typeof PrepararEntrevistaRoute
  '/vagas': typeof VagasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carta-editor': typeof AuthenticatedCartaEditorRoute
  '/cartas': typeof AuthenticatedCartasRoute
  '/entrevistas': typeof AuthenticatedEntrevistasRoute
  '/meus-cvs': typeof AuthenticatedMeusCvsRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/paysuite-webhook': typeof ApiPaysuiteWebhookRoute
  '/api/cron/ai-cost-alert': typeof ApiCronAiCostAlertRoute
  '/api/cron/plan-reminders': typeof ApiCronPlanRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/planos': typeof PlanosRoute
  '/preparar-entrevista': typeof PrepararEntrevistaRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carta-editor': typeof AuthenticatedCartaEditorRoute
  '/_authenticated/cartas': typeof AuthenticatedCartasRoute
  '/_authenticated/entrevistas': typeof AuthenticatedEntrevistasRoute
  '/_authenticated/meus-cvs': typeof AuthenticatedMeusCvsRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/api/paysuite-webhook': typeof ApiPaysuiteWebhookRoute
  '/api/cron/ai-cost-alert': typeof ApiCronAiCostAlertRoute
  '/api/cron/plan-reminders': typeof ApiCronPlanRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/auth'
    | '/editor'
    | '/planos'
    | '/preparar-entrevista'
    | '/vagas'
    | '/admin'
    | '/carta-editor'
    | '/cartas'
    | '/entrevistas'
    | '/meus-cvs'
    | '/perfil'
    | '/api/paysuite-webhook'
    | '/api/cron/ai-cost-alert'
    | '/api/cron/plan-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/auth'
    | '/editor'
    | '/planos'
    | '/preparar-entrevista'
    | '/vagas'
    | '/admin'
    | '/carta-editor'
    | '/cartas'
    | '/entrevistas'
    | '/meus-cvs'
    | '/perfil'
    | '/api/paysuite-webhook'
    | '/api/cron/ai-cost-alert'
    | '/api/cron/plan-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analise'
    | '/auth'
    | '/editor'
    | '/planos'
    | '/preparar-entrevista'
    | '/vagas'
    | '/_authenticated/admin'
    | '/_authenticated/carta-editor'
    | '/_authenticated/cartas'
    | '/_authenticated/entrevistas'
    | '/_authenticated/meus-cvs'
    | '/_authenticated/perfil'
    | '/api/paysuite-webhook'
    | '/api/cron/ai-cost-alert'
    | '/api/cron/plan-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnaliseRoute: typeof AnaliseRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRoute
  PlanosRoute: typeof PlanosRoute
  PrepararEntrevistaRoute: typeof PrepararEntrevistaRoute
  VagasRoute: typeof VagasRoute
  ApiPaysuiteWebhookRoute: typeof ApiPaysuiteWebhookRoute
  ApiCronAiCostAlertRoute: typeof ApiCronAiCostAlertRoute
  ApiCronPlanRemindersRoute: typeof ApiCronPlanRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparar-entrevista': {
      id: '/preparar-entrevista'
      path: '/preparar-entrevista'
      fullPath: '/preparar-entrevista'
      preLoaderRoute: typeof PrepararEntrevistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paysuite-webhook': {
      id: '/api/paysuite-webhook'
      path: '/api/paysuite-webhook'
      fullPath: '/api/paysuite-webhook'
      preLoaderRoute: typeof ApiPaysuiteWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-cvs': {
      id: '/_authenticated/meus-cvs'
      path: '/meus-cvs'
      fullPath: '/meus-cvs'
      preLoaderRoute: typeof AuthenticatedMeusCvsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas': {
      id: '/_authenticated/entrevistas'
      path: '/entrevistas'
      fullPath: '/entrevistas'
      preLoaderRoute: typeof AuthenticatedEntrevistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartas': {
      id: '/_authenticated/cartas'
      path: '/cartas'
      fullPath: '/cartas'
      preLoaderRoute: typeof AuthenticatedCartasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta-editor': {
      id: '/_authenticated/carta-editor'
      path: '/carta-editor'
      fullPath: '/carta-editor'
      preLoaderRoute: typeof AuthenticatedCartaEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/plan-reminders': {
      id: '/api/cron/plan-reminders'
      path: '/api/cron/plan-reminders'
      fullPath: '/api/cron/plan-reminders'
      preLoaderRoute: typeof ApiCronPlanRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/ai-cost-alert': {
      id: '/api/cron/ai-cost-alert'
      path: '/api/cron/ai-cost-alert'
      fullPath: '/api/cron/ai-cost-alert'
      preLoaderRoute: typeof ApiCronAiCostAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCartaEditorRoute: typeof AuthenticatedCartaEditorRoute
  AuthenticatedCartasRoute: typeof AuthenticatedCartasRoute
  AuthenticatedEntrevistasRoute: typeof AuthenticatedEntrevistasRoute
  AuthenticatedMeusCvsRoute: typeof AuthenticatedMeusCvsRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCartaEditorRoute: AuthenticatedCartaEditorRoute,
  AuthenticatedCartasRoute: AuthenticatedCartasRoute,
  AuthenticatedEntrevistasRoute: AuthenticatedEntrevistasRoute,
  AuthenticatedMeusCvsRoute: AuthenticatedMeusCvsRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnaliseRoute: AnaliseRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRoute,
  PlanosRoute: PlanosRoute,
  PrepararEntrevistaRoute: PrepararEntrevistaRoute,
  VagasRoute: VagasRoute,
  ApiPaysuiteWebhookRoute: ApiPaysuiteWebhookRoute,
  ApiCronAiCostAlertRoute: ApiCronAiCostAlertRoute,
  ApiCronPlanRemindersRoute: ApiCronPlanRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
