/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeusCvsRouteImport } from './routes/_authenticated/meus-cvs'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusCvsRoute = AuthenticatedMeusCvsRouteImport.update({
  id: '/meus-cvs',
  path: '/meus-cvs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/vagas': typeof VagasRoute
  '/meus-cvs': typeof AuthenticatedMeusCvsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/vagas': typeof VagasRoute
  '/meus-cvs': typeof AuthenticatedMeusCvsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/meus-cvs': typeof AuthenticatedMeusCvsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analise' | '/auth' | '/editor' | '/vagas' | '/meus-cvs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analise' | '/auth' | '/editor' | '/vagas' | '/meus-cvs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analise'
    | '/auth'
    | '/editor'
    | '/vagas'
    | '/_authenticated/meus-cvs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnaliseRoute: typeof AnaliseRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRoute
  VagasRoute: typeof VagasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-cvs': {
      id: '/_authenticated/meus-cvs'
      path: '/meus-cvs'
      fullPath: '/meus-cvs'
      preLoaderRoute: typeof AuthenticatedMeusCvsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeusCvsRoute: typeof AuthenticatedMeusCvsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeusCvsRoute: AuthenticatedMeusCvsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnaliseRoute: AnaliseRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRoute,
  VagasRoute: VagasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
