/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as PrepararEntrevistaRouteImport } from './routes/preparar-entrevista'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeusCvsRouteImport } from './routes/_authenticated/meus-cvs'
import { Route as AuthenticatedEntrevistasRouteImport } from './routes/_authenticated/entrevistas'
import { Route as AuthenticatedCartasRouteImport } from './routes/_authenticated/cartas'
import { Route as AuthenticatedCartaEditorRouteImport } from './routes/_authenticated/carta-editor'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepararEntrevistaRoute = PrepararEntrevistaRouteImport.update({
  id: '/preparar-entrevista',
  path: '/preparar-entrevista',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusCvsRoute = AuthenticatedMeusCvsRouteImport.update({
  id: '/meus-cvs',
  path: '/meus-cvs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntrevistasRoute =
  AuthenticatedEntrevistasRouteImport.update({
    id: '/entrevistas',
    path: '/entrevistas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartasRoute = AuthenticatedCartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartaEditorRoute =
  AuthenticatedCartaEditorRouteImport.update({
    id: '/carta-editor',
    path: '/carta-editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/preparar-entrevista': typeof PrepararEntrevistaRoute
  '/vagas': typeof VagasRoute
  '/carta-editor': typeof AuthenticatedCartaEditorRoute
  '/cartas': typeof AuthenticatedCartasRoute
  '/entrevistas': typeof AuthenticatedEntrevistasRoute
  '/meus-cvs': typeof AuthenticatedMeusCvsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/preparar-entrevista': typeof PrepararEntrevistaRoute
  '/vagas': typeof VagasRoute
  '/carta-editor': typeof AuthenticatedCartaEditorRoute
  '/cartas': typeof AuthenticatedCartasRoute
  '/entrevistas': typeof AuthenticatedEntrevistasRoute
  '/meus-cvs': typeof AuthenticatedMeusCvsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analise': typeof AnaliseRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/preparar-entrevista': typeof PrepararEntrevistaRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/carta-editor': typeof AuthenticatedCartaEditorRoute
  '/_authenticated/cartas': typeof AuthenticatedCartasRoute
  '/_authenticated/entrevistas': typeof AuthenticatedEntrevistasRoute
  '/_authenticated/meus-cvs': typeof AuthenticatedMeusCvsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/auth'
    | '/editor'
    | '/preparar-entrevista'
    | '/vagas'
    | '/carta-editor'
    | '/cartas'
    | '/entrevistas'
    | '/meus-cvs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/auth'
    | '/editor'
    | '/preparar-entrevista'
    | '/vagas'
    | '/carta-editor'
    | '/cartas'
    | '/entrevistas'
    | '/meus-cvs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analise'
    | '/auth'
    | '/editor'
    | '/preparar-entrevista'
    | '/vagas'
    | '/_authenticated/carta-editor'
    | '/_authenticated/cartas'
    | '/_authenticated/entrevistas'
    | '/_authenticated/meus-cvs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnaliseRoute: typeof AnaliseRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRoute
  PrepararEntrevistaRoute: typeof PrepararEntrevistaRoute
  VagasRoute: typeof VagasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparar-entrevista': {
      id: '/preparar-entrevista'
      path: '/preparar-entrevista'
      fullPath: '/preparar-entrevista'
      preLoaderRoute: typeof PrepararEntrevistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-cvs': {
      id: '/_authenticated/meus-cvs'
      path: '/meus-cvs'
      fullPath: '/meus-cvs'
      preLoaderRoute: typeof AuthenticatedMeusCvsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entrevistas': {
      id: '/_authenticated/entrevistas'
      path: '/entrevistas'
      fullPath: '/entrevistas'
      preLoaderRoute: typeof AuthenticatedEntrevistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartas': {
      id: '/_authenticated/cartas'
      path: '/cartas'
      fullPath: '/cartas'
      preLoaderRoute: typeof AuthenticatedCartasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta-editor': {
      id: '/_authenticated/carta-editor'
      path: '/carta-editor'
      fullPath: '/carta-editor'
      preLoaderRoute: typeof AuthenticatedCartaEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartaEditorRoute: typeof AuthenticatedCartaEditorRoute
  AuthenticatedCartasRoute: typeof AuthenticatedCartasRoute
  AuthenticatedEntrevistasRoute: typeof AuthenticatedEntrevistasRoute
  AuthenticatedMeusCvsRoute: typeof AuthenticatedMeusCvsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartaEditorRoute: AuthenticatedCartaEditorRoute,
  AuthenticatedCartasRoute: AuthenticatedCartasRoute,
  AuthenticatedEntrevistasRoute: AuthenticatedEntrevistasRoute,
  AuthenticatedMeusCvsRoute: AuthenticatedMeusCvsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnaliseRoute: AnaliseRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRoute,
  PrepararEntrevistaRoute: PrepararEntrevistaRoute,
  VagasRoute: VagasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
