// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylcsokafyoapziqjlmag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsY3Nva2FmeW9hcHppcWpsbWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2MjI2MDQsImV4cCI6MjA5NzE5ODYwNH0.Q2N80gTK2TB5G6JWoSyOUqud35hSbnuT8miYJk8rlMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});